#!/usr/bin/env tsx
/**
 * Theme Generation Script
 * Generates SCSS token files from CSP (Color Set Protocol) presets.
 *
 * Input:  @woosgem-dev/core presets (default, dark)
 * Output: src/tokens/_color-sets.scss, src/tokens/_colors.scss
 *
 * Run: pnpm generate:themes
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
// Direct source import — tsx resolves TS files, avoids pnpm exports issue
import {
  defaultTheme,
  darkTheme,
  generateColorSets,
  generateSCSSFile,
  type ResolvedColorTokens,
} from '../../ds-core/src/index';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tokensDir = path.join(__dirname, '../src/tokens');

/**
 * Static primitive values used at SCSS compile-time.
 * Extracted from the light theme preset — these are theme-independent base colors
 * needed for interpolation in component SCSS (tooltip bg, modal close, skeleton).
 */
const PRIMITIVES: Record<string, string> = {
  black: '#000000',
  white: '#FFFFFF',
  'gray-900': '#1A1A1A',
  'gray-700': '#4A4A4A',
  'gray-500': '#8A8A8A',
  'gray-300': '#C4C4C4',
  'gray-100': '#F5F5F5',
  'gray-50': '#FAFAFA',
};

/**
 * Generate _colors.scss — static primitives + CSS Custom Property references
 */
function generateColorsFile(tokenNames: string[], prefix: string): string {
  const lines: string[] = [];

  lines.push('// ===================');
  lines.push('// Color Tokens');
  lines.push('// ===================');
  lines.push('// Generated by Color Set Protocol (CSP)');
  lines.push('// Do not edit manually — run `pnpm generate`');
  lines.push('');

  // Static primitives (compile-time values for SCSS interpolation)
  lines.push('// Static Primitives (theme-independent, compile-time)');
  for (const [name, value] of Object.entries(PRIMITIVES)) {
    lines.push(`$${name}: ${value};`);
  }
  lines.push('');

  // Group tokens by category
  const groups: Record<string, string[]> = {};

  for (const name of tokenNames) {
    const category = getTokenCategory(name);
    if (!groups[category]) {
      groups[category] = [];
    }
    groups[category].push(name);
  }

  for (const [category, tokens] of Object.entries(groups)) {
    lines.push(`// ${category}`);
    for (const name of tokens) {
      const varName = name.replace(/-/g, '-');
      lines.push(`$${varName}: var(--${prefix}-${name});`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Categorize a token name for grouping in _colors.scss
 */
function getTokenCategory(name: string): string {
  if (name.startsWith('primary')) return 'Primary';
  if (name.startsWith('secondary')) return 'Secondary';
  if (name.startsWith('danger')) return 'Danger';
  if (name.startsWith('success')) return 'Success';
  if (name.startsWith('warning')) return 'Warning';
  if (name.startsWith('info')) return 'Info';
  if (name.startsWith('text')) return 'Text';
  if (name.startsWith('background')) return 'Background';
  if (name.startsWith('border')) return 'Border';
  if (name.startsWith('neutral')) return 'Neutral Scale';
  if (name.startsWith('surface')) return 'Surface';
  if (name.startsWith('input')) return 'Input';
  if (name.startsWith('link')) return 'Link';
  if (name.startsWith('state')) return 'State';
  if (name.startsWith('shadow')) return 'Shadow';
  if (name.startsWith('focus')) return 'Focus';
  if (name.includes('-light')) return 'Accent Light';
  return 'Other';
}

// Generate resolved color sets from presets
const resolved = generateColorSets([defaultTheme, darkTheme]);

// Generate _color-sets.scss
const colorSetsContent = generateSCSSFile(resolved, { includeComments: true });
const colorSetsPath = path.join(tokensDir, '_color-sets.scss');
fs.writeFileSync(colorSetsPath, colorSetsContent);
console.log(`[OK] ${path.relative(process.cwd(), colorSetsPath)}`);

// Generate _colors.scss
const tokenNames = Object.keys(resolved[0].tokens) as (keyof ResolvedColorTokens)[];
const colorsContent = generateColorsFile(tokenNames, 'wg-color');
const colorsPath = path.join(tokensDir, '_colors.scss');
fs.writeFileSync(colorsPath, colorsContent);
console.log(`[OK] ${path.relative(process.cwd(), colorsPath)}`);

console.log('\nTheme generation completed.');
