import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Alert variant options */
export const AlertVariants = ['filled', 'outline', 'subtle'] as const;
export type AlertVariant = (typeof AlertVariants)[number];

/** Alert status options */
export const AlertStatuses = ['info', 'success', 'warning', 'error'] as const;
export type AlertStatus = (typeof AlertStatuses)[number];

/** Style props for Alert component */
export interface AlertStyleProps {
  variant?: AlertVariant;
  status?: AlertStatus;
  closable?: boolean;
}

/** DOM attributes generated by Alert */
export interface AlertAttrs {
  class: string;
  'data-variant': AlertVariant;
  'data-status': AlertStatus;
  'data-closable'?: boolean | undefined;
  role: 'alert';
}

/** Alert component definition */
export const Alert = {
  displayName: 'Alert',

  defaultProps: {
    variant: 'subtle',
    status: 'info',
    closable: false,
  },

  propTypes: {
    variant: AlertVariants,
    status: AlertStatuses,
  },

  mapPropsToAttrs: (props: AlertStyleProps): AlertAttrs => {
    const merged = { ...Alert.defaultProps, ...filterNullish(props) };
    return {
      class: cls('alert'),
      'data-variant': merged.variant,
      'data-status': merged.status,
      'data-closable': merged.closable || undefined,
      role: 'alert',
    };
  },

  template: {
    tag: 'div',
    slots: ['icon', 'default', 'action'],
  },
} as const satisfies ComponentDefinition<AlertStyleProps, AlertAttrs, 'div'>;
