import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Avatar size options */
export const AvatarSizes = ['xs', 'sm', 'md', 'lg', 'xl'] as const;
export type AvatarSize = (typeof AvatarSizes)[number];

/** Avatar shape options */
export const AvatarShapes = ['circle', 'square'] as const;
export type AvatarShape = (typeof AvatarShapes)[number];

/** Style props for Avatar component */
export interface AvatarStyleProps {
  size?: AvatarSize;
  shape?: AvatarShape;
  src?: string;
  alt?: string;
  fallback?: string;
}

/** DOM attributes generated by Avatar */
export interface AvatarAttrs {
  class: string;
  'data-size': AvatarSize;
  'data-shape': AvatarShape;
  'data-has-image'?: boolean | undefined;
}

/** Avatar component definition */
export const Avatar = {
  displayName: 'Avatar',

  defaultProps: {
    size: 'md',
    shape: 'circle',
    src: '',
    alt: '',
    fallback: '',
  },

  propTypes: {
    size: AvatarSizes,
    shape: AvatarShapes,
  },

  mapPropsToAttrs: (props: AvatarStyleProps): AvatarAttrs => {
    const merged = { ...Avatar.defaultProps, ...filterNullish(props) };
    return {
      class: cls('avatar'),
      'data-size': merged.size,
      'data-shape': merged.shape,
      'data-has-image': merged.src ? true : undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<AvatarStyleProps, AvatarAttrs, 'div'>;
