import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Badge variant options */
export const BadgeVariants = ['solid', 'outline', 'subtle'] as const;
export type BadgeVariant = (typeof BadgeVariants)[number];

/** Badge color options */
export const BadgeColors = ['primary', 'secondary', 'danger', 'success', 'warning', 'info'] as const;
export type BadgeColor = (typeof BadgeColors)[number];

/** Badge size options */
export const BadgeSizes = ['sm', 'md', 'lg'] as const;
export type BadgeSize = (typeof BadgeSizes)[number];

/** Style props for Badge component */
export interface BadgeStyleProps {
  variant?: BadgeVariant;
  color?: BadgeColor;
  size?: BadgeSize;
}

/** DOM attributes generated by Badge */
export interface BadgeAttrs {
  class: string;
  'data-variant': BadgeVariant;
  'data-color': BadgeColor;
  'data-size': BadgeSize;
}

/** Badge component definition */
export const Badge = {
  displayName: 'Badge',

  defaultProps: {
    variant: 'solid',
    color: 'primary',
    size: 'md',
  },

  propTypes: {
    variant: BadgeVariants,
    color: BadgeColors,
    size: BadgeSizes,
  },

  mapPropsToAttrs: (props: BadgeStyleProps): BadgeAttrs => {
    const merged = { ...Badge.defaultProps, ...filterNullish(props) };
    return {
      class: cls('badge'),
      'data-variant': merged.variant,
      'data-color': merged.color,
      'data-size': merged.size,
    };
  },

  template: {
    tag: 'span',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<BadgeStyleProps, BadgeAttrs, 'span'>;
