import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Button variant options */
export const ButtonVariants = ['filled', 'outline', 'ghost', 'link'] as const;
export type ButtonVariant = (typeof ButtonVariants)[number];

/** Button color options */
export const ButtonColors = ['primary', 'secondary', 'danger', 'success', 'warning', 'info'] as const;
export type ButtonColor = (typeof ButtonColors)[number];

/** Button size options */
export const ButtonSizes = ['xs', 'sm', 'md', 'lg'] as const;
export type ButtonSize = (typeof ButtonSizes)[number];

/** Style props for Button component */
export interface ButtonStyleProps {
  variant?: ButtonVariant;
  color?: ButtonColor;
  size?: ButtonSize;
  loading?: boolean;
  disabled?: boolean;
  fullWidth?: boolean;
}

/** DOM attributes generated by Button */
export interface ButtonAttrs {
  class: string;
  'data-variant': ButtonVariant;
  'data-color': ButtonColor;
  'data-size': ButtonSize;
  'data-state'?: 'loading' | 'disabled' | undefined;
  'data-full-width'?: boolean | undefined;
  disabled?: boolean | undefined;
}

/** Button component definition */
export const Button = {
  displayName: 'Button',

  defaultProps: {
    variant: 'filled',
    color: 'primary',
    size: 'md',
    loading: false,
    disabled: false,
    fullWidth: false,
  },

  propTypes: {
    variant: ButtonVariants,
    color: ButtonColors,
    size: ButtonSizes,
  },

  mapPropsToAttrs: (props: ButtonStyleProps): ButtonAttrs => {
    const merged = { ...Button.defaultProps, ...filterNullish(props) };
    return {
      class: 'btn',
      'data-variant': merged.variant,
      'data-color': merged.color,
      'data-size': merged.size,
      'data-state': merged.loading ? 'loading' : merged.disabled ? 'disabled' : undefined,
      'data-full-width': merged.fullWidth || undefined,
      disabled: merged.disabled || merged.loading || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<ButtonStyleProps, ButtonAttrs, 'button'>;
