import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Card variant options */
export const CardVariants = ['outlined', 'elevated', 'filled'] as const;
export type CardVariant = (typeof CardVariants)[number];

/** Card padding options */
export const CardPaddings = ['none', 'sm', 'md', 'lg'] as const;
export type CardPadding = (typeof CardPaddings)[number];

/** Footer alignment options */
export const CardFooterAligns = ['start', 'center', 'end', 'between'] as const;
export type CardFooterAlign = (typeof CardFooterAligns)[number];

/** Style props for Card component */
export interface CardStyleProps {
  /** Visual variant */
  variant?: CardVariant;
  /** Inner padding */
  padding?: CardPadding;
  /** Show hover effect */
  hoverable?: boolean;
  /** Act as clickable button */
  clickable?: boolean;
}

/** DOM attributes generated by Card */
export interface CardAttrs {
  class: string;
  'data-variant': CardVariant;
  'data-padding': CardPadding;
  'data-hoverable'?: boolean | undefined;
  'data-clickable'?: boolean | undefined;
  role?: 'button' | undefined;
  tabIndex?: 0 | undefined;
}

/** Card component definition */
export const Card = {
  displayName: 'Card',

  defaultProps: {
    variant: 'outlined',
    padding: 'md',
    hoverable: false,
    clickable: false,
  },

  propTypes: {
    variant: CardVariants,
    padding: CardPaddings,
  },

  mapPropsToAttrs: (props: CardStyleProps): CardAttrs => {
    const merged = { ...Card.defaultProps, ...filterNullish(props) };
    return {
      class: 'card',
      'data-variant': merged.variant,
      'data-padding': merged.padding,
      'data-hoverable': merged.hoverable || merged.clickable || undefined,
      'data-clickable': merged.clickable || undefined,
      role: merged.clickable ? 'button' : undefined,
      tabIndex: merged.clickable ? 0 : undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default', 'header', 'footer'],
  },
} as const satisfies ComponentDefinition<CardStyleProps, CardAttrs, 'div'>;

// ============================================
// Compound Components: Card.Header, Card.Body, Card.Footer
// ============================================

/** Style props for CardHeader */
export interface CardHeaderStyleProps {
  /** Whether to show divider below header */
  divider?: boolean;
}

/** DOM attributes for CardHeader */
export interface CardHeaderAttrs {
  class: string;
  'data-divider'?: boolean | undefined;
}

/** CardHeader component definition */
export const CardHeader = {
  displayName: 'CardHeader',

  defaultProps: {
    divider: false,
  },

  propTypes: {},

  mapPropsToAttrs: (props: CardHeaderStyleProps): CardHeaderAttrs => {
    const merged = { ...CardHeader.defaultProps, ...filterNullish(props) };
    return {
      class: 'card-header',
      'data-divider': merged.divider || undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<CardHeaderStyleProps, CardHeaderAttrs, 'div'>;

/** DOM attributes for CardBody */
export interface CardBodyAttrs {
  class: string;
}

/** CardBody component definition - simple content wrapper */
export const CardBody = {
  displayName: 'CardBody',

  defaultProps: {},

  propTypes: {},

  mapPropsToAttrs: (): CardBodyAttrs => {
    return {
      class: 'card-body',
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<Record<string, never>, CardBodyAttrs, 'div'>;

// CardBody has no style props, export empty interface for consistency
export interface CardBodyStyleProps {}

/** Style props for CardFooter */
export interface CardFooterStyleProps {
  /** Whether to show divider above footer */
  divider?: boolean;
  /** Alignment of footer content */
  align?: CardFooterAlign;
}

/** DOM attributes for CardFooter */
export interface CardFooterAttrs {
  class: string;
  'data-divider'?: boolean | undefined;
  'data-align'?: CardFooterAlign | undefined;
}

/** CardFooter component definition */
export const CardFooter = {
  displayName: 'CardFooter',

  defaultProps: {
    divider: false,
    align: 'start',
  },

  propTypes: {
    align: CardFooterAligns,
  },

  mapPropsToAttrs: (props: CardFooterStyleProps): CardFooterAttrs => {
    const merged = { ...CardFooter.defaultProps, ...filterNullish(props) };
    return {
      class: 'card-footer',
      'data-divider': merged.divider || undefined,
      'data-align': merged.align,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<CardFooterStyleProps, CardFooterAttrs, 'div'>;
