import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Divider orientation options */
export const DividerOrientations = ['horizontal', 'vertical'] as const;
export type DividerOrientation = (typeof DividerOrientations)[number];

/** Divider variant options */
export const DividerVariants = ['solid', 'dashed'] as const;
export type DividerVariant = (typeof DividerVariants)[number];

/** Divider spacing options */
export const DividerSpacings = ['none', 'sm', 'md', 'lg'] as const;
export type DividerSpacing = (typeof DividerSpacings)[number];

/** Divider color options */
export const DividerColors = ['default', 'muted', 'primary', 'secondary', 'danger', 'success'] as const;
export type DividerColor = (typeof DividerColors)[number];

/** Style props for Divider component */
export interface DividerStyleProps {
  orientation?: DividerOrientation;
  variant?: DividerVariant;
  spacing?: DividerSpacing;
  color?: DividerColor;
}

/** DOM attributes generated by Divider */
export interface DividerAttrs {
  class: string;
  'data-orientation': DividerOrientation;
  'data-variant': DividerVariant;
  'data-spacing': DividerSpacing;
  'data-color': DividerColor;
  role: 'separator';
  'aria-orientation': DividerOrientation;
}

/** Divider component definition */
export const Divider = {
  displayName: 'Divider',

  defaultProps: {
    orientation: 'horizontal',
    variant: 'solid',
    spacing: 'md',
    color: 'default',
  },

  propTypes: {
    orientation: DividerOrientations,
    variant: DividerVariants,
    spacing: DividerSpacings,
    color: DividerColors,
  },

  mapPropsToAttrs: (props: DividerStyleProps): DividerAttrs => {
    const merged = { ...Divider.defaultProps, ...filterNullish(props) };
    return {
      class: 'divider',
      role: 'separator',
      'data-orientation': merged.orientation,
      'data-variant': merged.variant,
      'data-spacing': merged.spacing,
      'data-color': merged.color,
      'aria-orientation': merged.orientation,
    };
  },

  template: {
    tag: 'hr',
    slots: [],
  },
} as const satisfies ComponentDefinition<DividerStyleProps, DividerAttrs, 'hr'>;
