import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** IconButton variant options */
export const IconButtonVariants = ['filled', 'outline', 'ghost'] as const;
export type IconButtonVariant = (typeof IconButtonVariants)[number];

/** IconButton color options */
export const IconButtonColors = ['primary', 'secondary', 'danger'] as const;
export type IconButtonColor = (typeof IconButtonColors)[number];

/** IconButton size options */
export const IconButtonSizes = ['xs', 'sm', 'md', 'lg'] as const;
export type IconButtonSize = (typeof IconButtonSizes)[number];

/** IconButton shape options */
export const IconButtonShapes = ['square', 'circle'] as const;
export type IconButtonShape = (typeof IconButtonShapes)[number];

/** Style props for IconButton component */
export interface IconButtonStyleProps {
  variant?: IconButtonVariant;
  color?: IconButtonColor;
  size?: IconButtonSize;
  shape?: IconButtonShape;
  disabled?: boolean;
}

/** DOM attributes generated by IconButton */
export interface IconButtonAttrs {
  class: string;
  'data-variant': IconButtonVariant;
  'data-color': IconButtonColor;
  'data-size': IconButtonSize;
  'data-shape': IconButtonShape;
  'data-state'?: 'disabled' | undefined;
  disabled?: boolean | undefined;
}

/** IconButton component definition */
export const IconButton = {
  displayName: 'IconButton',

  defaultProps: {
    variant: 'filled',
    color: 'primary',
    size: 'md',
    shape: 'square',
    disabled: false,
  },

  propTypes: {
    variant: IconButtonVariants,
    color: IconButtonColors,
    size: IconButtonSizes,
    shape: IconButtonShapes,
  },

  mapPropsToAttrs: (props: IconButtonStyleProps): IconButtonAttrs => {
    const merged = { ...IconButton.defaultProps, ...filterNullish(props) };
    return {
      class: 'icon-btn',
      'data-variant': merged.variant,
      'data-color': merged.color,
      'data-size': merged.size,
      'data-shape': merged.shape,
      'data-state': merged.disabled ? 'disabled' : undefined,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<IconButtonStyleProps, IconButtonAttrs, 'button'>;
