import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Icon size options */
export const IconSizes = ['xs', 'sm', 'md', 'lg', 'xl'] as const;
export type IconSize = (typeof IconSizes)[number];

/** Icon color options */
export const IconColors = [
  'inherit',
  'primary',
  'secondary',
  'danger',
  'success',
  'warning',
  'info',
  'muted',
] as const;
export type IconColor = (typeof IconColors)[number];

/** Style props for Icon component */
export interface IconStyleProps {
  /** Icon size - xs: 12px, sm: 16px, md: 20px, lg: 24px, xl: 32px */
  size?: IconSize;
  /** Icon color - uses currentColor by default */
  color?: IconColor;
}

/** DOM attributes generated by Icon */
export interface IconAttrs {
  class: string;
  'data-size': IconSize;
  'data-color': IconColor;
  'aria-hidden': true;
}

/** Icon component definition */
export const Icon = {
  displayName: 'Icon',

  defaultProps: {
    size: 'md',
    color: 'inherit',
  },

  propTypes: {
    size: IconSizes,
    color: IconColors,
  },

  mapPropsToAttrs: (props: IconStyleProps): IconAttrs => {
    const merged = { ...Icon.defaultProps, ...filterNullish(props) };
    return {
      class: 'icon',
      'data-size': merged.size,
      'data-color': merged.color,
      'aria-hidden': true,
    };
  },

  template: {
    tag: 'span',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<IconStyleProps, IconAttrs, 'span'>;

/** Size to pixel mapping */
export const IconSizeMap = {
  xs: 12,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
} as const;
