import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Input variant options */
export const InputVariants = ['outline', 'filled', 'underline'] as const;
export type InputVariant = (typeof InputVariants)[number];

/** Input size options */
export const InputSizes = ['sm', 'md', 'lg'] as const;
export type InputSize = (typeof InputSizes)[number];

/**
 * Style props for Input component.
 *
 * @remarks
 * For accessibility, always provide:
 * - `id` - Required for label association (`<label htmlFor="id">`)
 * - `name` - Required for form submission
 * - `aria-describedby` - Reference to error/help text element
 * - `aria-label` or associated `<label>` - Required for screen readers
 *
 * @example
 * ```tsx
 * <label htmlFor="email">Email</label>
 * <Input
 *   id="email"
 *   name="email"
 *   type="email"
 *   required
 *   error={!!errors.email}
 *   aria-describedby="email-error"
 * />
 * <span id="email-error">{errors.email}</span>
 * ```
 */
export interface InputStyleProps {
  /** Visual variant */
  variant?: InputVariant;
  /** Size of the input */
  size?: InputSize;
  /** Shows error state. Automatically sets aria-invalid="true" */
  error?: boolean;
  /** Shows success state */
  success?: boolean;
  /** Disables the input */
  disabled?: boolean;
}

/** DOM attributes generated by Input */
export interface InputAttrs {
  class: string;
  'data-variant': InputVariant;
  'data-size': InputSize;
  'data-state'?: 'error' | 'success' | 'disabled' | undefined;
  'aria-invalid'?: 'true' | undefined;
  disabled?: boolean | undefined;
}

/** Input component definition */
export const Input = {
  displayName: 'Input',

  defaultProps: {
    variant: 'outline',
    size: 'md',
    error: false,
    success: false,
    disabled: false,
  },

  propTypes: {
    variant: InputVariants,
    size: InputSizes,
  },

  mapPropsToAttrs: (props: InputStyleProps): InputAttrs => {
    const merged = { ...Input.defaultProps, ...filterNullish(props) };
    const state = merged.error ? 'error' : merged.success ? 'success' : merged.disabled ? 'disabled' : undefined;
    return {
      class: 'input',
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-state': state,
      'aria-invalid': merged.error ? 'true' : undefined,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'input',
    slots: [],
  },
} as const satisfies ComponentDefinition<InputStyleProps, InputAttrs, 'input'>;
