import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Kbd size options */
export const KbdSizes = ['sm', 'md', 'lg'] as const;
export type KbdSize = (typeof KbdSizes)[number];

/** Kbd variant options */
export const KbdVariants = ['raised', 'flat', 'outline'] as const;
export type KbdVariant = (typeof KbdVariants)[number];

/** Style props for Kbd component */
export interface KbdStyleProps {
  /** Size of the keyboard key */
  size?: KbdSize;
  /** Visual variant */
  variant?: KbdVariant;
}

/** DOM attributes generated by Kbd */
export interface KbdAttrs {
  class: string;
  'data-size': KbdSize;
  'data-variant': KbdVariant;
}

/** Kbd component definition */
export const Kbd = {
  displayName: 'Kbd',

  defaultProps: {
    size: 'sm',
    variant: 'raised',
  },

  propTypes: {
    size: KbdSizes,
    variant: KbdVariants,
  },

  mapPropsToAttrs: (props: KbdStyleProps): KbdAttrs => {
    const merged = { ...Kbd.defaultProps, ...filterNullish(props) };
    return {
      class: cls('kbd'),
      'data-size': merged.size,
      'data-variant': merged.variant,
    };
  },

  template: {
    tag: 'kbd',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<KbdStyleProps, KbdAttrs, 'kbd'>;
