import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** ListItem variant options */
export const ListItemVariants = ['default', 'interactive'] as const;
export type ListItemVariant = (typeof ListItemVariants)[number];

/** Style props for ListItem component */
export interface ListItemStyleProps {
  variant?: ListItemVariant;
  selected?: boolean;
  disabled?: boolean;
  divider?: boolean;
}

/** DOM attributes generated by ListItem */
export interface ListItemAttrs {
  class: string;
  'data-variant': ListItemVariant;
  'data-state'?: 'selected' | 'disabled' | 'selected-disabled' | undefined;
  'data-divider'?: boolean | undefined;
  'aria-selected'?: boolean | undefined;
  'aria-disabled'?: boolean | undefined;
}

/** ListItem component definition */
export const ListItem = {
  displayName: 'ListItem',

  defaultProps: {
    variant: 'default',
    selected: false,
    disabled: false,
    divider: false,
  },

  propTypes: {
    variant: ListItemVariants,
  },

  mapPropsToAttrs: (props: ListItemStyleProps): ListItemAttrs => {
    const merged = { ...ListItem.defaultProps, ...filterNullish(props) };

    let state: ListItemAttrs['data-state'];
    if (merged.selected && merged.disabled) {
      state = 'selected-disabled';
    } else if (merged.selected) {
      state = 'selected';
    } else if (merged.disabled) {
      state = 'disabled';
    }

    return {
      class: cls('list-item'),
      'data-variant': merged.variant,
      'data-state': state,
      'data-divider': merged.divider || undefined,
      'aria-selected': merged.selected || undefined,
      'aria-disabled': merged.disabled || undefined,
    };
  },

  template: {
    tag: 'li',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<ListItemStyleProps, ListItemAttrs, 'li'>;
