import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Modal size options */
export const ModalSizes = ['sm', 'md', 'lg', 'xl', 'full'] as const;
export type ModalSize = (typeof ModalSizes)[number];

/** Style props for Modal component */
export interface ModalStyleProps {
  /** Whether the modal is open */
  open?: boolean;
  /** Modal size */
  size?: ModalSize;
  /** Whether the modal can be closed via close button or ESC key */
  closable?: boolean;
}

/** DOM attributes generated by Modal */
export interface ModalAttrs {
  class: string;
  'data-size': ModalSize;
  'data-open'?: boolean | undefined;
  'data-closable'?: boolean | undefined;
  role: 'dialog';
  'aria-modal': boolean;
  'aria-hidden': boolean;
}

/** Modal component definition */
export const Modal = {
  displayName: 'Modal',

  defaultProps: {
    open: false,
    size: 'md',
    closable: true,
  },

  propTypes: {
    size: ModalSizes,
  },

  mapPropsToAttrs: (props: ModalStyleProps): ModalAttrs => {
    const merged = { ...Modal.defaultProps, ...filterNullish(props) };
    return {
      class: 'modal',
      'data-size': merged.size,
      'data-open': merged.open || undefined,
      'data-closable': merged.closable || undefined,
      role: 'dialog',
      'aria-modal': true,
      'aria-hidden': !merged.open,
    };
  },

  template: {
    tag: 'div',
    slots: ['header', 'default', 'footer'],
  },
} as const satisfies ComponentDefinition<ModalStyleProps, ModalAttrs, 'div'>;

/** Modal Header component definition */
export interface ModalHeaderStyleProps {
  /** Whether to show close button */
  showClose?: boolean;
}

export interface ModalHeaderAttrs {
  class: string;
  'data-show-close'?: boolean | undefined;
}

export const ModalHeader = {
  displayName: 'ModalHeader',

  defaultProps: {
    showClose: true,
  },

  propTypes: {},

  mapPropsToAttrs: (props: ModalHeaderStyleProps): ModalHeaderAttrs => {
    const merged = { ...ModalHeader.defaultProps, ...filterNullish(props) };
    return {
      class: 'modal-header',
      'data-show-close': merged.showClose || undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default', 'close'],
  },
} as const satisfies ComponentDefinition<ModalHeaderStyleProps, ModalHeaderAttrs, 'div'>;

/** Modal Body component definition */
export interface ModalBodyStyleProps {
  /** Enable scrolling within the body */
  scrollable?: boolean;
}

export interface ModalBodyAttrs {
  class: string;
  'data-scrollable'?: boolean | undefined;
}

export const ModalBody = {
  displayName: 'ModalBody',

  defaultProps: {
    scrollable: true,
  },

  propTypes: {},

  mapPropsToAttrs: (props: ModalBodyStyleProps): ModalBodyAttrs => {
    const merged = { ...ModalBody.defaultProps, ...filterNullish(props) };
    return {
      class: 'modal-body',
      'data-scrollable': merged.scrollable || undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<ModalBodyStyleProps, ModalBodyAttrs, 'div'>;

/** Modal Footer component definition */
export interface ModalFooterStyleProps {
  /** Alignment of footer content */
  align?: 'start' | 'center' | 'end';
}

export interface ModalFooterAttrs {
  class: string;
  'data-align': 'start' | 'center' | 'end';
}

export const ModalFooter = {
  displayName: 'ModalFooter',

  defaultProps: {
    align: 'end',
  },

  propTypes: {
    align: ['start', 'center', 'end'] as const,
  },

  mapPropsToAttrs: (props: ModalFooterStyleProps): ModalFooterAttrs => {
    const merged = { ...ModalFooter.defaultProps, ...filterNullish(props) };
    return {
      class: 'modal-footer',
      'data-align': merged.align,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<ModalFooterStyleProps, ModalFooterAttrs, 'div'>;
