import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Overlay opacity options */
export const OverlayOpacities = ['light', 'medium', 'dark'] as const;
export type OverlayOpacity = (typeof OverlayOpacities)[number];

/** Overlay z-index level options */
export const OverlayLevels = ['base', 'dropdown', 'modal', 'popover', 'toast'] as const;
export type OverlayLevel = (typeof OverlayLevels)[number];

/** Style props for Overlay component */
export interface OverlayStyleProps {
  /** Enable background blur effect */
  blur?: boolean;
  /** Background opacity level */
  opacity?: OverlayOpacity;
  /** Z-index stacking level */
  level?: OverlayLevel;
  /** Whether the overlay is visible (for animation states) */
  visible?: boolean;
}

/** DOM attributes generated by Overlay */
export interface OverlayAttrs {
  class: string;
  'data-blur'?: boolean | undefined;
  'data-opacity': OverlayOpacity;
  'data-level': OverlayLevel;
  'data-visible'?: boolean | undefined;
  'aria-hidden': boolean;
}

/** Overlay component definition */
export const Overlay = {
  displayName: 'Overlay',

  defaultProps: {
    blur: false,
    opacity: 'medium',
    level: 'modal',
    visible: true,
  },

  propTypes: {
    opacity: OverlayOpacities,
    level: OverlayLevels,
  },

  mapPropsToAttrs: (props: OverlayStyleProps): OverlayAttrs => {
    const merged = { ...Overlay.defaultProps, ...filterNullish(props) };
    return {
      class: 'overlay',
      'data-blur': merged.blur || undefined,
      'data-opacity': merged.opacity,
      'data-level': merged.level,
      'data-visible': merged.visible || undefined,
      'aria-hidden': !merged.visible,
    };
  },

  template: {
    tag: 'div',
    slots: [],
  },
} as const satisfies ComponentDefinition<OverlayStyleProps, OverlayAttrs, 'div'>;
