import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Progress variant options */
export const ProgressVariants = ['default', 'gradient'] as const;
export type ProgressVariant = (typeof ProgressVariants)[number];

/** Progress color options */
export const ProgressColors = ['primary', 'success', 'warning', 'danger', 'neutral'] as const;
export type ProgressColor = (typeof ProgressColors)[number];

/** Progress size options */
export const ProgressSizes = ['sm', 'md', 'lg'] as const;
export type ProgressSize = (typeof ProgressSizes)[number];

/** Style props for Progress component */
export interface ProgressStyleProps {
  variant?: ProgressVariant;
  color?: ProgressColor;
  size?: ProgressSize;
  /** Current progress value (0-100 by default, or 0-max if max is specified) */
  value?: number;
  /** Maximum value (default: 100) */
  max?: number;
  /** Show percentage label inside the progress bar */
  showLabel?: boolean;
}

/** DOM attributes generated by Progress */
export interface ProgressAttrs {
  class: string;
  'data-variant': ProgressVariant;
  'data-color': ProgressColor;
  'data-size': ProgressSize;
  'data-show-label'?: boolean | undefined;
  role: 'progressbar';
  'aria-valuenow': number;
  'aria-valuemin': number;
  'aria-valuemax': number;
  /** CSS custom property for fill percentage (0-100) */
  style: string;
}

/** Progress component definition */
export const Progress = {
  displayName: 'Progress',

  defaultProps: {
    variant: 'default',
    color: 'primary',
    size: 'md',
    value: 0,
    max: 100,
    showLabel: false,
  },

  propTypes: {
    variant: ProgressVariants,
    color: ProgressColors,
    size: ProgressSizes,
  },

  mapPropsToAttrs: (props: ProgressStyleProps): ProgressAttrs => {
    const merged = { ...Progress.defaultProps, ...filterNullish(props) };
    
    // Clamp value between 0 and max
    const max = Math.max(merged.max, 0);
    const value = Math.max(0, Math.min(merged.value, max));
    const percentage = max > 0 ? (value / max) * 100 : 0;

    return {
      class: cls('progress'),
      'data-variant': merged.variant,
      'data-color': merged.color,
      'data-size': merged.size,
      'data-show-label': merged.showLabel || undefined,
      role: 'progressbar',
      'aria-valuenow': value,
      'aria-valuemin': 0,
      'aria-valuemax': max,
      style: `--progress-value: ${percentage}%`,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<ProgressStyleProps, ProgressAttrs, 'div'>;

/**
 * Utility function to get the percentage value from props.
 * Useful for rendering the label in framework wrappers.
 */
export function getProgressPercentage(value: number = 0, max: number = 100): number {
  const safeMax = Math.max(max, 0);
  const safeValue = Math.max(0, Math.min(value, safeMax));
  return safeMax > 0 ? Math.round((safeValue / safeMax) * 100) : 0;
}
