import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Radio size options */
export const RadioSizes = ['sm', 'md', 'lg'] as const;
export type RadioSize = (typeof RadioSizes)[number];

/** Radio color options */
export const RadioColors = ['primary', 'secondary', 'success'] as const;
export type RadioColor = (typeof RadioColors)[number];

/** Style props for Radio component */
export interface RadioStyleProps {
  size?: RadioSize;
  color?: RadioColor;
  checked?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by Radio */
export interface RadioAttrs {
  class: string;
  'data-size': RadioSize;
  'data-color': RadioColor;
  'data-state'?: 'checked' | 'disabled' | 'checked-disabled' | undefined;
  role: 'radio';
  'aria-checked': boolean;
  disabled?: boolean | undefined;
}

/** Radio component definition */
export const Radio = {
  displayName: 'Radio',

  defaultProps: {
    size: 'md',
    color: 'primary',
    checked: false,
    disabled: false,
  },

  propTypes: {
    size: RadioSizes,
    color: RadioColors,
  },

  mapPropsToAttrs: (props: RadioStyleProps): RadioAttrs => {
    const merged = { ...Radio.defaultProps, ...filterNullish(props) };

    let state: RadioAttrs['data-state'];
    if (merged.checked && merged.disabled) {
      state = 'checked-disabled';
    } else if (merged.checked) {
      state = 'checked';
    } else if (merged.disabled) {
      state = 'disabled';
    }

    return {
      class: cls('radio'),
      'data-size': merged.size,
      'data-color': merged.color,
      'data-state': state,
      role: 'radio',
      'aria-checked': merged.checked,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: ['label'],
  },
} as const satisfies ComponentDefinition<RadioStyleProps, RadioAttrs, 'button'>;

/** RadioGroup component for managing multiple radios */
export interface RadioGroupStyleProps {
  orientation?: 'horizontal' | 'vertical';
  disabled?: boolean;
}

export interface RadioGroupAttrs {
  class: string;
  'data-orientation': 'horizontal' | 'vertical';
  role: 'radiogroup';
  'aria-disabled'?: boolean | undefined;
}

export const RadioGroup = {
  displayName: 'RadioGroup',

  defaultProps: {
    orientation: 'vertical',
    disabled: false,
  },

  propTypes: {
    orientation: ['horizontal', 'vertical'] as const,
  },

  mapPropsToAttrs: (props: RadioGroupStyleProps): RadioGroupAttrs => {
    const merged = { ...RadioGroup.defaultProps, ...filterNullish(props) };
    return {
      class: cls('radio-group'),
      'data-orientation': merged.orientation,
      role: 'radiogroup',
      'aria-disabled': merged.disabled || undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<RadioGroupStyleProps, RadioGroupAttrs, 'div'>;
