import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls, clsEl } from '../constants';

/** SegmentedControl size options */
export const SegmentedControlSizes = ['sm', 'md', 'lg'] as const;
export type SegmentedControlSize = (typeof SegmentedControlSizes)[number];

/** Style props for SegmentedControl component */
export interface SegmentedControlStyleProps {
  size?: SegmentedControlSize;
  fullWidth?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by SegmentedControl */
export interface SegmentedControlAttrs {
  class: string;
  'data-size': SegmentedControlSize;
  'data-full-width'?: boolean | undefined;
  'data-disabled'?: boolean | undefined;
  role: 'group';
}

/** Style props for SegmentedControlItem component */
export interface SegmentedControlItemStyleProps {
  selected?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by SegmentedControlItem */
export interface SegmentedControlItemAttrs {
  class: string;
  'data-state'?: 'selected' | 'disabled' | undefined;
  'aria-selected'?: boolean | undefined;
  disabled?: boolean | undefined;
}

/** SegmentedControl component definition */
export const SegmentedControl = {
  displayName: 'SegmentedControl',

  defaultProps: {
    size: 'md',
    fullWidth: false,
    disabled: false,
  },

  propTypes: {
    size: SegmentedControlSizes,
  },

  mapPropsToAttrs: (props: SegmentedControlStyleProps): SegmentedControlAttrs => {
    const merged = { ...SegmentedControl.defaultProps, ...filterNullish(props) };
    return {
      class: cls('segmented-control'),
      role: 'group',
      'data-size': merged.size,
      'data-full-width': merged.fullWidth || undefined,
      'data-disabled': merged.disabled || undefined,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<SegmentedControlStyleProps, SegmentedControlAttrs, 'div'>;

/** SegmentedControlItem component definition */
export const SegmentedControlItem = {
  displayName: 'SegmentedControlItem',

  defaultProps: {
    selected: false,
    disabled: false,
  },

  propTypes: {},

  mapPropsToAttrs: (props: SegmentedControlItemStyleProps): SegmentedControlItemAttrs => {
    const merged = { ...SegmentedControlItem.defaultProps, ...filterNullish(props) };
    return {
      class: clsEl('segmented-control', 'item'),
      'data-state': merged.selected ? 'selected' : merged.disabled ? 'disabled' : undefined,
      'aria-selected': merged.selected || undefined,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<SegmentedControlItemStyleProps, SegmentedControlItemAttrs, 'button'>;
