import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls, clsEl } from '../constants';

/** Select variant options */
export const SelectVariants = ['outline', 'filled'] as const;
export type SelectVariant = (typeof SelectVariants)[number];

/** Select size options */
export const SelectSizes = ['sm', 'md', 'lg'] as const;
export type SelectSize = (typeof SelectSizes)[number];

/** Select option type */
export interface SelectOption {
  /** Option value */
  value: string;
  /** Display label */
  label: string;
  /** Disabled state */
  disabled?: boolean;
}

/** Style props for Select component (trigger button) */
export interface SelectStyleProps {
  variant?: SelectVariant;
  size?: SelectSize;
  disabled?: boolean;
  error?: boolean;
  open?: boolean;
  multiple?: boolean;
}

/** DOM attributes generated by Select trigger */
export interface SelectAttrs {
  class: string;
  'data-variant': SelectVariant;
  'data-size': SelectSize;
  'data-state'?: 'error' | 'disabled' | 'open' | undefined;
  'data-multiple'?: boolean | undefined;
  role: 'combobox';
  'aria-expanded': boolean;
  'aria-haspopup': 'listbox';
  'aria-disabled'?: boolean | undefined;
  disabled?: boolean | undefined;
}

/** Select component definition (trigger button) */
export const Select = {
  displayName: 'Select',

  defaultProps: {
    variant: 'outline',
    size: 'md',
    disabled: false,
    error: false,
    open: false,
    multiple: false,
  },

  propTypes: {
    variant: SelectVariants,
    size: SelectSizes,
  },

  mapPropsToAttrs: (props: SelectStyleProps): SelectAttrs => {
    const merged = { ...Select.defaultProps, ...filterNullish(props) };

    // State priority: disabled > error > open
    let state: SelectAttrs['data-state'];
    if (merged.disabled) {
      state = 'disabled';
    } else if (merged.error) {
      state = 'error';
    } else if (merged.open) {
      state = 'open';
    }

    return {
      class: cls('select'),
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-state': state,
      'data-multiple': merged.multiple || undefined,
      role: 'combobox',
      'aria-expanded': merged.open,
      'aria-haspopup': 'listbox',
      'aria-disabled': merged.disabled || undefined,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: ['value', 'placeholder', 'icon'],
  },
} as const satisfies ComponentDefinition<SelectStyleProps, SelectAttrs, 'button'>;

/** Style props for SelectMenu (dropdown listbox) */
export interface SelectMenuStyleProps {
  size?: SelectSize;
  open?: boolean;
  multiple?: boolean;
}

/** DOM attributes generated by SelectMenu */
export interface SelectMenuAttrs {
  class: string;
  'data-size': SelectSize;
  'data-state'?: 'open' | undefined;
  role: 'listbox';
  'aria-multiselectable'?: boolean | undefined;
}

/** SelectMenu component definition (dropdown container) */
export const SelectMenu = {
  displayName: 'SelectMenu',

  defaultProps: {
    size: 'md',
    open: false,
    multiple: false,
  },

  propTypes: {
    size: SelectSizes,
  },

  mapPropsToAttrs: (props: SelectMenuStyleProps): SelectMenuAttrs => {
    const merged = { ...SelectMenu.defaultProps, ...filterNullish(props) };
    return {
      class: clsEl('select', 'menu'),
      'data-size': merged.size,
      'data-state': merged.open ? 'open' : undefined,
      role: 'listbox',
      'aria-multiselectable': merged.multiple || undefined,
    };
  },

  template: {
    tag: 'ul',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<SelectMenuStyleProps, SelectMenuAttrs, 'ul'>;

/** Style props for SelectOption (list item) */
export interface SelectOptionStyleProps {
  size?: SelectSize;
  selected?: boolean;
  disabled?: boolean;
  highlighted?: boolean;
}

/** DOM attributes generated by SelectOption */
export interface SelectOptionAttrs {
  class: string;
  'data-size': SelectSize;
  'data-state'?: 'selected' | 'disabled' | 'selected-disabled' | 'highlighted' | undefined;
  role: 'option';
  'aria-selected': boolean;
  'aria-disabled'?: boolean | undefined;
}

/** SelectOption component definition (list item) */
export const SelectOption = {
  displayName: 'SelectOption',

  defaultProps: {
    size: 'md',
    selected: false,
    disabled: false,
    highlighted: false,
  },

  propTypes: {
    size: SelectSizes,
  },

  mapPropsToAttrs: (props: SelectOptionStyleProps): SelectOptionAttrs => {
    const merged = { ...SelectOption.defaultProps, ...filterNullish(props) };

    // State priority: selected+disabled > disabled > highlighted > selected
    let state: SelectOptionAttrs['data-state'];
    if (merged.selected && merged.disabled) {
      state = 'selected-disabled';
    } else if (merged.disabled) {
      state = 'disabled';
    } else if (merged.highlighted) {
      state = 'highlighted';
    } else if (merged.selected) {
      state = 'selected';
    }

    return {
      class: clsEl('select', 'option'),
      'data-size': merged.size,
      'data-state': state,
      role: 'option',
      'aria-selected': merged.selected,
      'aria-disabled': merged.disabled || undefined,
    };
  },

  template: {
    tag: 'li',
    slots: ['default', 'checkmark'],
  },
} as const satisfies ComponentDefinition<SelectOptionStyleProps, SelectOptionAttrs, 'li'>;
