import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Skeleton variant options */
export const SkeletonVariants = ['text', 'circular', 'rectangular'] as const;
export type SkeletonVariant = (typeof SkeletonVariants)[number];

/** Skeleton size options */
export const SkeletonSizes = ['sm', 'md', 'lg', 'full'] as const;
export type SkeletonSize = (typeof SkeletonSizes)[number];

/** Skeleton animation options */
export const SkeletonAnimations = ['pulse', 'wave', 'none'] as const;
export type SkeletonAnimation = (typeof SkeletonAnimations)[number];

/** Style props for Skeleton component */
export interface SkeletonStyleProps {
  variant?: SkeletonVariant;
  size?: SkeletonSize;
  animation?: SkeletonAnimation;
  width?: string | number | undefined;
  height?: string | number | undefined;
}

/** DOM attributes generated by Skeleton */
export interface SkeletonAttrs {
  class: string;
  'data-variant': SkeletonVariant;
  'data-size': SkeletonSize;
  'data-animation': SkeletonAnimation;
  'aria-busy': true;
  'aria-live': 'polite';
  style?: string | undefined;
}

/** Helper to format dimension value */
const formatDimension = (value: string | number | undefined): string | undefined => {
  if (value === undefined) return undefined;
  if (typeof value === 'number') return `${value}px`;
  return value;
};

/** Skeleton component definition */
export const Skeleton = {
  displayName: 'Skeleton',

  defaultProps: {
    variant: 'text',
    size: 'md',
    animation: 'pulse',
    width: undefined,
    height: undefined,
  },

  propTypes: {
    variant: SkeletonVariants,
    size: SkeletonSizes,
    animation: SkeletonAnimations,
  },

  mapPropsToAttrs: (props: SkeletonStyleProps): SkeletonAttrs => {
    const merged = { ...Skeleton.defaultProps, ...filterNullish(props) };

    const width = formatDimension(props.width);
    const height = formatDimension(props.height);

    const styleParts: string[] = [];
    if (width) styleParts.push(`width: ${width}`);
    if (height) styleParts.push(`height: ${height}`);

    return {
      class: 'skeleton',
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-animation': merged.animation,
      'aria-busy': true,
      'aria-live': 'polite',
      style: styleParts.length > 0 ? styleParts.join('; ') : undefined,
    };
  },

  template: {
    tag: 'div',
    slots: [],
  },
} as const satisfies ComponentDefinition<SkeletonStyleProps, SkeletonAttrs, 'div'>;
