import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Spinner size options */
export const SpinnerSizes = ['xs', 'sm', 'md', 'lg'] as const;
export type SpinnerSize = (typeof SpinnerSizes)[number];

/** Spinner color options */
export const SpinnerColors = ['primary', 'secondary', 'muted', 'current'] as const;
export type SpinnerColor = (typeof SpinnerColors)[number];

/** Style props for Spinner component */
export interface SpinnerStyleProps {
  size?: SpinnerSize;
  color?: SpinnerColor;
  label?: string;
}

/** DOM attributes generated by Spinner */
export interface SpinnerAttrs {
  class: string;
  'data-size': SpinnerSize;
  'data-color': SpinnerColor;
  role: 'status';
  'aria-label': string;
}

/** Spinner component definition */
export const Spinner = {
  displayName: 'Spinner',

  defaultProps: {
    size: 'md',
    color: 'primary',
    label: 'Loading...',
  },

  propTypes: {
    size: SpinnerSizes,
    color: SpinnerColors,
  },

  mapPropsToAttrs: (props: SpinnerStyleProps): SpinnerAttrs => {
    const merged = { ...Spinner.defaultProps, ...filterNullish(props) };
    return {
      class: cls('spinner'),
      'data-size': merged.size,
      'data-color': merged.color,
      role: 'status',
      'aria-label': merged.label,
    };
  },

  template: {
    tag: 'div',
    slots: [],
  },
} as const satisfies ComponentDefinition<SpinnerStyleProps, SpinnerAttrs, 'div'>;
