import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Switch size options */
export const SwitchSizes = ['sm', 'md', 'lg'] as const;
export type SwitchSize = (typeof SwitchSizes)[number];

/** Switch color options */
export const SwitchColors = ['primary', 'secondary', 'success'] as const;
export type SwitchColor = (typeof SwitchColors)[number];

/** Style props for Switch component */
export interface SwitchStyleProps {
  size?: SwitchSize;
  color?: SwitchColor;
  checked?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by Switch */
export interface SwitchAttrs {
  class: string;
  'data-size': SwitchSize;
  'data-color': SwitchColor;
  'data-state'?: 'checked' | 'disabled' | 'checked-disabled' | undefined;
  role: 'switch';
  'aria-checked': boolean;
  disabled?: boolean | undefined;
}

/** Switch component definition */
export const Switch = {
  displayName: 'Switch',

  defaultProps: {
    size: 'md',
    color: 'primary',
    checked: false,
    disabled: false,
  },

  propTypes: {
    size: SwitchSizes,
    color: SwitchColors,
  },

  mapPropsToAttrs: (props: SwitchStyleProps): SwitchAttrs => {
    const merged = { ...Switch.defaultProps, ...filterNullish(props) };

    let state: SwitchAttrs['data-state'];
    if (merged.checked && merged.disabled) {
      state = 'checked-disabled';
    } else if (merged.checked) {
      state = 'checked';
    } else if (merged.disabled) {
      state = 'disabled';
    }

    return {
      class: cls('switch'),
      'data-size': merged.size,
      'data-color': merged.color,
      'data-state': state,
      role: 'switch',
      'aria-checked': merged.checked,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: [],
  },
} as const satisfies ComponentDefinition<SwitchStyleProps, SwitchAttrs, 'button'>;
