import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls } from '../constants';

/** Tab variant options */
export const TabVariants = ['underline', 'filled'] as const;
export type TabVariant = (typeof TabVariants)[number];

/** Tab size options */
export const TabSizes = ['sm', 'md', 'lg'] as const;
export type TabSize = (typeof TabSizes)[number];

/** Tab color options */
export const TabColors = ['primary', 'secondary'] as const;
export type TabColor = (typeof TabColors)[number];

/** Style props for Tab component */
export interface TabStyleProps {
  variant?: TabVariant;
  size?: TabSize;
  color?: TabColor;
  selected?: boolean;
  disabled?: boolean;
  fullWidth?: boolean;
}

/** DOM attributes generated by Tab */
export interface TabAttrs {
  class: string;
  'data-variant': TabVariant;
  'data-size': TabSize;
  'data-color': TabColor;
  'data-state'?: 'selected' | 'disabled' | undefined;
  'data-full-width'?: boolean | undefined;
  disabled?: boolean | undefined;
  'aria-selected'?: boolean | undefined;
  role: 'tab';
}

/** Tab component definition */
export const Tab = {
  displayName: 'Tab',

  defaultProps: {
    variant: 'underline',
    size: 'md',
    color: 'primary',
    selected: false,
    disabled: false,
    fullWidth: false,
  },

  propTypes: {
    variant: TabVariants,
    size: TabSizes,
    color: TabColors,
  },

  mapPropsToAttrs: (props: TabStyleProps): TabAttrs => {
    const merged = { ...Tab.defaultProps, ...filterNullish(props) };
    return {
      class: cls('tab'),
      role: 'tab',
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-color': merged.color,
      'data-state': merged.selected ? 'selected' : merged.disabled ? 'disabled' : undefined,
      'data-full-width': merged.fullWidth || undefined,
      'aria-selected': merged.selected || undefined,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'button',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TabStyleProps, TabAttrs, 'button'>;
