import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';
import { cls, clsEl } from '../constants';

/** Table variant options */
export const TableVariants = ['default', 'striped', 'bordered'] as const;
export type TableVariant = (typeof TableVariants)[number];

/** Table size options */
export const TableSizes = ['sm', 'md', 'lg'] as const;
export type TableSize = (typeof TableSizes)[number];

/** Table cell alignment options */
export const TableAligns = ['left', 'center', 'right'] as const;
export type TableAlign = (typeof TableAligns)[number];

// ============================================
// Table
// ============================================

/** Style props for Table component */
export interface TableStyleProps {
  /** Visual variant */
  variant?: TableVariant;
  /** Table density */
  size?: TableSize;
  /** Show hover effect on rows */
  hoverable?: boolean;
}

/** DOM attributes generated by Table */
export interface TableAttrs {
  class: string;
  'data-variant': TableVariant;
  'data-size': TableSize;
  'data-hoverable'?: boolean | undefined;
}

/** Table component definition */
export const Table = {
  displayName: 'Table',

  defaultProps: {
    variant: 'default',
    size: 'md',
    hoverable: false,
  },

  propTypes: {
    variant: TableVariants,
    size: TableSizes,
  },

  mapPropsToAttrs: (props: TableStyleProps): TableAttrs => {
    const merged = { ...Table.defaultProps, ...filterNullish(props) };
    return {
      class: cls('table'),
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-hoverable': merged.hoverable || undefined,
    };
  },

  template: {
    tag: 'table',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TableStyleProps, TableAttrs, 'table'>;

// ============================================
// TableHead
// ============================================

/** DOM attributes for TableHead */
export interface TableHeadAttrs {
  class: string;
}

/** TableHead component definition */
export const TableHead = {
  displayName: 'TableHead',

  defaultProps: {},

  propTypes: {},

  mapPropsToAttrs: (): TableHeadAttrs => {
    return {
      class: clsEl('table', 'head'),
    };
  },

  template: {
    tag: 'thead',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<Record<string, never>, TableHeadAttrs, 'thead'>;

// TableHead has no style props, export empty interface for consistency
export interface TableHeadStyleProps {}

// ============================================
// TableBody
// ============================================

/** DOM attributes for TableBody */
export interface TableBodyAttrs {
  class: string;
}

/** TableBody component definition */
export const TableBody = {
  displayName: 'TableBody',

  defaultProps: {},

  propTypes: {},

  mapPropsToAttrs: (): TableBodyAttrs => {
    return {
      class: clsEl('table', 'body'),
    };
  },

  template: {
    tag: 'tbody',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<Record<string, never>, TableBodyAttrs, 'tbody'>;

// TableBody has no style props, export empty interface for consistency
export interface TableBodyStyleProps {}

// ============================================
// TableRow
// ============================================

/** Style props for TableRow */
export interface TableRowStyleProps {
  /** Whether the row is selected */
  selected?: boolean;
}

/** DOM attributes for TableRow */
export interface TableRowAttrs {
  class: string;
  'data-state'?: 'selected' | undefined;
  'aria-selected'?: 'true' | undefined;
}

/** TableRow component definition */
export const TableRow = {
  displayName: 'TableRow',

  defaultProps: {
    selected: false,
  },

  propTypes: {},

  mapPropsToAttrs: (props: TableRowStyleProps): TableRowAttrs => {
    const merged = { ...TableRow.defaultProps, ...filterNullish(props) };
    return {
      class: clsEl('table', 'row'),
      'data-state': merged.selected ? 'selected' : undefined,
      'aria-selected': merged.selected ? 'true' : undefined,
    };
  },

  template: {
    tag: 'tr',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TableRowStyleProps, TableRowAttrs, 'tr'>;

// ============================================
// TableCell
// ============================================

/** Style props for TableCell */
export interface TableCellStyleProps {
  /** Text alignment */
  align?: TableAlign;
}

/** DOM attributes for TableCell */
export interface TableCellAttrs {
  class: string;
  'data-align': TableAlign;
}

/** TableCell component definition */
export const TableCell = {
  displayName: 'TableCell',

  defaultProps: {
    align: 'left',
  },

  propTypes: {
    align: TableAligns,
  },

  mapPropsToAttrs: (props: TableCellStyleProps): TableCellAttrs => {
    const merged = { ...TableCell.defaultProps, ...filterNullish(props) };
    return {
      class: clsEl('table', 'cell'),
      'data-align': merged.align,
    };
  },

  template: {
    tag: 'td',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TableCellStyleProps, TableCellAttrs, 'td'>;

// ============================================
// TableHeaderCell
// ============================================

/** Style props for TableHeaderCell */
export interface TableHeaderCellStyleProps {
  /** Text alignment */
  align?: TableAlign;
  /** Whether the column is sortable */
  sortable?: boolean;
}

/** DOM attributes for TableHeaderCell */
export interface TableHeaderCellAttrs {
  class: string;
  'data-align': TableAlign;
  'data-sortable'?: boolean | undefined;
  scope: 'col';
}

/** TableHeaderCell component definition */
export const TableHeaderCell = {
  displayName: 'TableHeaderCell',

  defaultProps: {
    align: 'left',
    sortable: false,
  },

  propTypes: {
    align: TableAligns,
  },

  mapPropsToAttrs: (props: TableHeaderCellStyleProps): TableHeaderCellAttrs => {
    const merged = { ...TableHeaderCell.defaultProps, ...filterNullish(props) };
    return {
      class: clsEl('table', 'header-cell'),
      'data-align': merged.align,
      'data-sortable': merged.sortable || undefined,
      scope: 'col',
    };
  },

  template: {
    tag: 'th',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TableHeaderCellStyleProps, TableHeaderCellAttrs, 'th'>;
