import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Tag variant options */
export const TagVariants = ['solid', 'outline', 'subtle'] as const;
export type TagVariant = (typeof TagVariants)[number];

/** Tag color options */
export const TagColors = ['primary', 'secondary', 'danger', 'success', 'warning', 'info'] as const;
export type TagColor = (typeof TagColors)[number];

/** Tag size options */
export const TagSizes = ['sm', 'md', 'lg'] as const;
export type TagSize = (typeof TagSizes)[number];

/** Style props for Tag component */
export interface TagStyleProps {
  variant?: TagVariant;
  color?: TagColor;
  size?: TagSize;
  closable?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by Tag */
export interface TagAttrs {
  class: string;
  'data-variant': TagVariant;
  'data-color': TagColor;
  'data-size': TagSize;
  'data-closable'?: boolean | undefined;
  'data-state'?: 'disabled' | undefined;
  'aria-disabled'?: 'true' | undefined;
}

/** Tag component definition */
export const Tag = {
  displayName: 'Tag',

  defaultProps: {
    variant: 'subtle',
    color: 'primary',
    size: 'md',
    closable: false,
    disabled: false,
  },

  propTypes: {
    variant: TagVariants,
    color: TagColors,
    size: TagSizes,
  },

  mapPropsToAttrs: (props: TagStyleProps): TagAttrs => {
    const merged = { ...Tag.defaultProps, ...filterNullish(props) };
    return {
      class: 'tag',
      'data-variant': merged.variant,
      'data-color': merged.color,
      'data-size': merged.size,
      'data-closable': merged.closable || undefined,
      'data-state': merged.disabled ? 'disabled' : undefined,
      'aria-disabled': merged.disabled ? 'true' : undefined,
    };
  },

  template: {
    tag: 'span',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TagStyleProps, TagAttrs, 'span'>;
