import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Textarea variant options */
export const TextareaVariants = ['outline', 'filled'] as const;
export type TextareaVariant = (typeof TextareaVariants)[number];

/** Textarea size options */
export const TextareaSizes = ['sm', 'md', 'lg'] as const;
export type TextareaSize = (typeof TextareaSizes)[number];

/** Textarea resize options */
export const TextareaResizes = ['none', 'vertical', 'horizontal', 'both'] as const;
export type TextareaResize = (typeof TextareaResizes)[number];

/** Style props for Textarea component */
export interface TextareaStyleProps {
  variant?: TextareaVariant;
  size?: TextareaSize;
  resize?: TextareaResize;
  disabled?: boolean;
  error?: boolean;
}

/** DOM attributes generated by Textarea */
export interface TextareaAttrs {
  class: string;
  'data-variant': TextareaVariant;
  'data-size': TextareaSize;
  'data-resize': TextareaResize;
  'data-state'?: 'disabled' | 'error' | undefined;
  disabled?: boolean | undefined;
  'aria-invalid'?: boolean | undefined;
}

/** Textarea component definition */
export const Textarea = {
  displayName: 'Textarea',

  defaultProps: {
    variant: 'outline',
    size: 'md',
    resize: 'vertical',
    disabled: false,
    error: false,
  },

  propTypes: {
    variant: TextareaVariants,
    size: TextareaSizes,
    resize: TextareaResizes,
  },

  mapPropsToAttrs: (props: TextareaStyleProps): TextareaAttrs => {
    const merged = { ...Textarea.defaultProps, ...filterNullish(props) };

    // disabled가 error보다 우선
    const state = merged.disabled ? 'disabled' : merged.error ? 'error' : undefined;

    return {
      class: 'textarea',
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-resize': merged.resize,
      'data-state': state,
      disabled: merged.disabled || undefined,
      'aria-invalid': merged.error || undefined,
    };
  },

  template: {
    tag: 'textarea',
    slots: [],
  },
} as const satisfies ComponentDefinition<TextareaStyleProps, TextareaAttrs, 'textarea'>;
