import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Toast variant options */
export const ToastVariants = ['info', 'success', 'warning', 'error'] as const;
export type ToastVariant = (typeof ToastVariants)[number];

/** Toast position options */
export const ToastPositions = [
  'top-right',
  'top-left',
  'bottom-right',
  'bottom-left',
  'top-center',
  'bottom-center',
] as const;
export type ToastPosition = (typeof ToastPositions)[number];

/** Style props for Toast component */
export interface ToastStyleProps {
  /** Visual style variant indicating the type of message */
  variant?: ToastVariant;
  /** Position where toast appears on screen */
  position?: ToastPosition;
  /** Auto-dismiss duration in milliseconds (0 = no auto-dismiss) */
  duration?: number;
  /** Whether to show close button */
  closable?: boolean;
  /** Whether toast is visible */
  visible?: boolean;
}

/** DOM attributes generated by Toast */
export interface ToastAttrs {
  class: string;
  'data-variant': ToastVariant;
  'data-position': ToastPosition;
  'data-closable'?: boolean | undefined;
  'data-visible'?: boolean | undefined;
  role: 'alert';
  'aria-live': 'polite';
  'aria-atomic': 'true';
}

/** Toast component definition */
export const Toast = {
  displayName: 'Toast',

  defaultProps: {
    variant: 'info',
    position: 'top-right',
    duration: 5000,
    closable: true,
    visible: true,
  },

  propTypes: {
    variant: ToastVariants,
    position: ToastPositions,
  },

  mapPropsToAttrs: (props: ToastStyleProps): ToastAttrs => {
    const merged = { ...Toast.defaultProps, ...filterNullish(props) };
    return {
      class: 'toast',
      'data-variant': merged.variant,
      'data-position': merged.position,
      'data-closable': merged.closable || undefined,
      'data-visible': merged.visible || undefined,
      role: 'alert',
      'aria-live': 'polite',
      'aria-atomic': 'true',
    };
  },

  template: {
    tag: 'div',
    slots: ['icon', 'default', 'action'],
  },
} as const satisfies ComponentDefinition<ToastStyleProps, ToastAttrs, 'div'>;
