import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Tooltip position options */
export const TooltipPositions = ['top', 'bottom', 'left', 'right'] as const;
export type TooltipPosition = (typeof TooltipPositions)[number];

/** Tooltip trigger options */
export const TooltipTriggers = ['hover', 'click', 'focus'] as const;
export type TooltipTrigger = (typeof TooltipTriggers)[number];

/** Style props for Tooltip component */
export interface TooltipStyleProps {
  /** Tooltip content text */
  content?: string;
  /** Position relative to trigger element */
  position?: TooltipPosition;
  /** Event that triggers tooltip */
  trigger?: TooltipTrigger;
  /** Delay before showing tooltip (in ms) */
  delay?: number;
  /** Whether to show arrow */
  arrow?: boolean;
  /** Whether the tooltip is visible (controlled mode) */
  visible?: boolean;
  /** Whether the tooltip is disabled */
  disabled?: boolean;
}

/** DOM attributes generated by Tooltip */
export interface TooltipAttrs {
  class: string;
  'data-position': TooltipPosition;
  'data-trigger': TooltipTrigger;
  'data-arrow'?: boolean | undefined;
  'data-visible'?: boolean | undefined;
  'data-disabled'?: boolean | undefined;
  role: 'tooltip';
}

/** Tooltip component definition */
export const Tooltip = {
  displayName: 'Tooltip',

  defaultProps: {
    content: '',
    position: 'top',
    trigger: 'hover',
    delay: 0,
    arrow: true,
    visible: false,
    disabled: false,
  },

  propTypes: {
    position: TooltipPositions,
    trigger: TooltipTriggers,
  },

  mapPropsToAttrs: (props: TooltipStyleProps): TooltipAttrs => {
    const merged = { ...Tooltip.defaultProps, ...filterNullish(props) };
    return {
      class: 'tooltip',
      'data-position': merged.position,
      'data-trigger': merged.trigger,
      'data-arrow': merged.arrow || undefined,
      'data-visible': merged.visible || undefined,
      'data-disabled': merged.disabled || undefined,
      role: 'tooltip',
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<TooltipStyleProps, TooltipAttrs, 'div'>;
